import type { Metadata } from "next";
import { ArrowDown, BriefcaseBusiness, CheckCircle2, ClipboardCheck, MessageCircle, Send } from "lucide-react";
import { getAnalytics } from "@/backend/services/queries";

export const metadata: Metadata = { title: "Analitik | Applyo" };
export default async function AnalyticsPage() {
  const analytics = await getAnalytics(); const metrics = [["Total lamaran", analytics.total, "var(--blue)"], ["Wawancara", analytics.interviews, "var(--pink)"], ["Asesmen", analytics.assessments, "var(--orange)"], ["Tawaran", analytics.offers, "var(--green)"]] as const; const trend = analytics.trend.slice(-6); const trendMax = Math.max(1, ...trend.map((item) => item.count)); const sourceMax = Math.max(1, ...analytics.sources.map((item) => item.applications));
  if (!analytics.total) return <div className="analytics-page"><header className="workspace-page-header"><div><span>Perkembangan pencarian kerja</span><h1>Analitik</h1></div></header><section className="calendar-empty"><BriefcaseBusiness /><strong>Belum ada data analitik.</strong><p>Analitik muncul setelah kamu menambahkan lamaran.</p></section></div>;
  return <div className="analytics-page"><header className="workspace-page-header"><div><span>Perkembangan pencarian kerja</span><h1>Analitik</h1><p>Lihat pola prosesmu tanpa skor produktivitas.</p></div></header><section className="analytics-metrics">{metrics.map(([label, value, color]) => <article style={{ background: color }} key={label}><strong>{value}</strong><span>{label}</span></article>)}</section><div className="analytics-layout"><section className="trend-section"><header><div><h2>Lamaran dari waktu ke waktu</h2><p>Enam periode terakhir</p></div><BriefcaseBusiness /></header><div className="bar-chart" role="img" aria-label={`${trend.length} periode data lamaran`}>{trend.map((item) => <div className="bar-item" key={item.date}><span>{item.count}</span><div style={{ height: `${(item.count / trendMax) * 100}%` }} /><small>{new Intl.DateTimeFormat("id-ID", { month: "short" }).format(new Date(item.date))}</small></div>)}</div></section><section className="funnel-section"><header><h2>Alur konversi</h2></header><div className="conversion-funnel"><div className="funnel-step funnel-applied"><Send /><span><strong>{analytics.total}</strong>Total</span></div><ArrowDown /><div className="funnel-step funnel-interview"><MessageCircle /><span><strong>{analytics.interviews}</strong>Wawancara</span></div><ArrowDown /><div className="funnel-step funnel-offer"><ClipboardCheck /><span><strong>{analytics.offers}</strong>Tawaran</span></div><ArrowDown /><div className="funnel-step funnel-hired"><CheckCircle2 /><span><strong>{analytics.hired}</strong>Diterima</span></div></div></section></div><section className="source-section"><header><div><h2>Sumber lamaran</h2><p>Tempat kamu menemukan peluang.</p></div></header><div className="source-list">{analytics.sources.map((item) => <div key={item.source}><strong>{item.source}</strong><span>{item.applications} lamaran</span><i style={{ width: `${(item.applications / sourceMax) * 100}%` }} /></div>)}</div></section></div>;
}
