import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import { databaseError } from "@/backend/errors";
import type { CreateEventInput, UpdateEventInput } from "@/backend/schemas/events";
import type { Database } from "@/types/database";

type Client = SupabaseClient<Database>;
const columns = "id,user_id,application_id,category,subtype,title,scheduled_at,deadline_at,location,url,notes,status,completed_at,created_at,updated_at";
function fields(input: CreateEventInput | UpdateEventInput) { return Object.fromEntries(Object.entries({ category: input.category, subtype: input.subtype, title: input.title, scheduled_at: input.scheduledAt, deadline_at: input.deadlineAt, location: input.location, url: input.url, notes: input.notes, status: input.status, completed_at: input.completedAt }).filter(([, value]) => value !== undefined)); }
export async function verifyOwnedApplication(client: Client, userId: string, applicationId: string) { const { data, error } = await client.from("applications").select("id").eq("id", applicationId).eq("user_id", userId).maybeSingle(); if (error) throw databaseError("verify_application", error); if (!data) throw databaseError("verify_application", { code: "PGRST116" }); }
export async function insertEvent(client: Client, userId: string, input: CreateEventInput) { await verifyOwnedApplication(client, userId, input.applicationId); const { data, error } = await client.from("recruitment_events").insert({ ...fields(input), user_id: userId, application_id: input.applicationId } as never).select(columns).single(); if (error) throw databaseError("create_event", error); return data; }
export async function patchEvent(client: Client, userId: string, input: UpdateEventInput) { const { data, error } = await client.from("recruitment_events").update(fields(input) as never).eq("id", input.eventId).eq("user_id", userId).select(columns).single(); if (error) throw databaseError("update_event", error); return data; }
export async function setEventComplete(client: Client, userId: string, eventId: string, completed: boolean, completedAt?: string) { const { data: current, error: readError } = await client.from("recruitment_events").select("status").eq("id", eventId).eq("user_id", userId).maybeSingle(); if (readError) throw databaseError("read_event", readError); if (!current) throw databaseError("read_event", { code: "PGRST116" }); if (current.status === "cancelled") throw databaseError("complete_event", { code: "22023" }); const { data, error } = await client.from("recruitment_events").update({ status: completed ? "completed" : "scheduled", completed_at: completed ? completedAt ?? new Date().toISOString() : null }).eq("id", eventId).eq("user_id", userId).select(columns).single(); if (error) throw databaseError("complete_event", error); return data; }
export async function removeEvent(client: Client, userId: string, eventId: string) { const { error, count } = await client.from("recruitment_events").delete({ count: "exact" }).eq("id", eventId).eq("user_id", userId); if (error) throw databaseError("delete_event", error); if (!count) throw databaseError("delete_event", { code: "PGRST116" }); }
