import "server-only";
import { requireAuth } from "@/backend/auth";
import { databaseError, validationError } from "@/backend/errors";
import { patchApplication, removeApplication, setArchived } from "@/backend/repositories/applications";
import { archiveApplicationSchema, closeApplicationSchema, createApplicationSchema, deleteApplicationSchema, moveApplicationSchema, reopenApplicationSchema, updateApplicationSchema } from "@/backend/schemas/applications";

function parse<T>(result: { success: true; data: T } | { success: false; error: import("zod").ZodError<T> }) { if (!result.success) throw validationError(result.error); return result.data; }
export async function createApplication(raw: unknown) { const input = parse(createApplicationSchema.safeParse(raw)); const { client } = await requireAuth(); const { data, error } = await client.rpc("create_application", { p_company: input.company, p_position: input.position, p_stage_id: input.stageId, p_job_url: input.jobUrl, p_location: input.location, p_work_arrangement: input.workArrangement, p_employment_type: input.employmentType, p_source: input.source, p_applied_at: input.appliedAt, p_salary_min: input.salaryMin, p_salary_max: input.salaryMax, p_currency: input.currency, p_job_description: input.jobDescription, p_notes: input.notes }); if (error) throw databaseError("create_application", error); return data; }
export async function updateApplication(raw: unknown) { const input = parse(updateApplicationSchema.safeParse(raw)); const { client, user } = await requireAuth(); if (input.salaryMin !== undefined || input.salaryMax !== undefined) { const { data: current, error } = await client.from("applications").select("salary_min,salary_max").eq("id", input.applicationId).eq("user_id", user.id).maybeSingle(); if (error) throw databaseError("read_application_salary", error); if (!current) throw databaseError("read_application_salary", { code: "PGRST116" }); const minimum = input.salaryMin === undefined ? current.salary_min : input.salaryMin; const maximum = input.salaryMax === undefined ? current.salary_max : input.salaryMax; if (minimum != null && maximum != null && maximum < minimum) throw validationError(updateApplicationSchema.safeParse({ applicationId: input.applicationId, salaryMin: minimum, salaryMax: maximum }).error!); } return patchApplication(client, user.id, input); }
export async function deleteApplication(raw: unknown) { const input = parse(deleteApplicationSchema.safeParse(raw)); const { client, user } = await requireAuth(); await removeApplication(client, user.id, input.applicationId); return { applicationId: input.applicationId }; }
export async function archiveApplication(raw: unknown) { const input = parse(archiveApplicationSchema.safeParse(raw)); const { client, user } = await requireAuth(); return setArchived(client, user.id, input.applicationId, input.archived); }
export async function moveApplication(raw: unknown) { const input = parse(moveApplicationSchema.safeParse(raw)); const { client } = await requireAuth(); const { data, error } = await client.rpc("move_application", { p_application_id: input.applicationId, p_destination_stage_id: input.destinationStageId, p_before_application_id: input.beforeApplicationId, p_after_application_id: input.afterApplicationId }); if (error) throw databaseError("move_application", error); return data; }
export async function closeApplication(raw: unknown) { const input = parse(closeApplicationSchema.safeParse(raw)); const { client } = await requireAuth(); const { data: stage, error: stageError } = await client.from("pipeline_stages").select("system_key,is_closed").eq("id", input.outcomeStageId).eq("system_key", input.outcome).eq("is_closed", true).maybeSingle(); if (stageError) throw databaseError("validate_outcome_stage", stageError); if (!stage) throw databaseError("validate_outcome_stage", { code: "PGRST116" }); const { data, error } = await client.rpc("close_application", { p_application_id: input.applicationId, p_outcome_stage_id: input.outcomeStageId, p_reason_code: input.reasonCode, p_notes: input.notes }); if (error) throw databaseError("close_application", error); return data; }
export async function reopenApplication(raw: unknown) { const input = parse(reopenApplicationSchema.safeParse(raw)); const { client } = await requireAuth(); const { data, error } = await client.rpc("reopen_application", { p_application_id: input.applicationId, p_destination_stage_id: input.destinationStageId }); if (error) throw databaseError("reopen_application", error); return data; }
